
spring.application.name=empowher

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=PqWeR$098
spring.datasource.driver-class-name=org.postgresql.Driver

# Prevent Hibernate from modifying your existing DB
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=empowher_db
